[greeter]
background = /usr/share/pixmaps/lockscreen-wallpaper.jpg
default-user-image = /usr/share/pixmaps/jigglypuff.jpg
theme-name = Catppuccin-Dark
clock-format = %Y-%m-%d %a %I:%M %p
font-name = JetBrainsMonoNL Nerd Font 10
