[Greeter]
logo=/usr/share/pixmaps/sigmarch.png
theme-name=Catppuccin-Dark
icon-theme-name=Adwaita
cursor-theme-name=phinger-cursors-dark
background=/usr/share/pixmaps/MIFFY BETTER.jpg
stretch-background-across-monitors=false
draw-grid=false
clock-format=%Y-%m-%d %a %I:%M %p
font-name=JetBrainsMonoNL Nerd Font 10
