import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetBrainsMonoNL NF"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL NF"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Regular"

[window]
decorations = "None"
opacity = 0.8
